[FIX] package: correctly name package entry files
Files are named o-spreadsheet[...] in package.json but
rollup generates o_spreadsheet[...] files

as a result any import fails because it's looking for a file that doesn't exist

`import { Model } from @odoo/o-spreadsheet`

=> Error: Cannot find module '/home/odoo/odoo/upgrade-spreadsheet-data/node_modules/@odoo/o-spreadsheet/dist/o-spreadsheet.cjs.js'.
   Please verify that the package.json has a valid "main" entry

closes odoo/o-spreadsheet#2196

X-original-commit: ebc1eedcfd086261d67fb40536db405b2d00db05
Signed-off-by: Rémi Rahir (rar) <rar@odoo.com>
Signed-off-by: Lucas Lefèvre (lul) <lul@odoo.com>