[FIX] package: correctly name package entry files
Files are named o-spreadsheet[...] in package.json but
rollup generates o_spreadsheet[...] files

as a result any import fails because it's looking for a file that doesn't exist

`import { Model } from @odoo/o-spreadsheet`

=> Error: Cannot find module '/home/odoo/odoo/upgrade-spreadsheet-data/node_modules/@odoo/o-spreadsheet/dist/o-spreadsheet.cjs.js'.
   Please verify that the package.json has a valid "main" entry

closes odoo/o-spreadsheet#2192

X-original-commit: fccf6dcf9330b377df521c021a1f62a882bcbe2f
Signed-off-by: Rémi Rahir (rar) <rar@odoo.com>
Signed-off-by: Lucas Lefèvre (lul) <lul@odoo.com>